### ISSUE TITLE
apply ruff ruleset B flake8-bugbear

### ISSUE THREAD

**Issue by davidhopkinson26** [azukds/tubular#112]
make code compliant with rule set and then add to ruleset in .ruff.toml

https://beta.ruff.rs/docs/rules/#flake8-bugbear-b

21 errors

**Comment by davidhopkinson26** [comment]
`tubular/base.py:163:13: B028 No explicit `stacklevel` keyword argument found
tubular/base.py:372:26: B006 Do not use mutable data structures for argument defaults
tubular/capping.py:179:13: B028 No explicit `stacklevel` keyword argument found
tubular/dates.py:230:13: B028 No explicit `stacklevel` keyword argument found
tubular/dates.py:296:28: B006 Do not use mutable data structures for argument defaults
tubular/dates.py:403:26: B006 Do not use mutable data structures for argument defaults
tubular/dates.py:619:13: B028 No explicit `stacklevel` keyword argument found
tubular/dates.py:712:17: B006 Do not use mutable data structures for argument defaults
tubular/dates.py:713:27: B006 Do not use mutable data structures for argument defaults
tubular/dates.py:912:21: B904 Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
tubular/imputers.py:330:21: B028 No explicit `stacklevel` keyword argument found
tubular/mapping.py:189:17: B028 No explicit `stacklevel` keyword argument found
tubular/mapping.py:194:17: B028 No explicit `stacklevel` keyword argument found
tubular/mapping.py:216:21: B028 No explicit `stacklevel` keyword argument found
tubular/misc.py:83:13: B904 Within an `except` clause, raise exceptions with `raise ... from err` or `raise ... from None` to distinguish them from errors in exception handling
tubular/nominal.py:701:49: B023 Function definition does not bind loop variable `level`
tubular/nominal.py:1134:21: B028 No explicit `stacklevel` keyword argument found
tubular/numeric.py:167:60: B006 Do not use mutable data structures for argument defaults
tubular/numeric.py:266:26: B006 Do not use mutable data structures for argument defaults
tubular/numeric.py:346:60: B006 Do not use mutable data structures for argument defaults
tubular/strings.py:57:26: B006 Do not use mutable data structures for argument defaults`

**Comment by ClaireF57** [comment]
Hi @davidhopkinson26 , @Sarah-TaylorKnight 
May I be assigned to this task ?

**Comment by davidhopkinson26** [comment]
addressed in #131
